console.log(Math.random())
console.log(Math.abs(-4))
console.log(Math.ceil(2.1))
console.log(Math.floor(5.7))
console.log(Math.round(4.4))
console.log(Math.PI)
console.log(Math.pow(2, 5))
console.log(Math.trunc(3.7))
console.log(Math.sign(5))
console.log(Math.sqrt(15))
console.log(Math.min(...[2, 3, 4]))
console.log(Math.max(2, 3, 4))
console.log(Math.log(4, 2))