list = ("Php", "Javascript", "Python", "C++", "Java", "C", "SQL", "Typescript")
print(list)
print(list[0])
print(list[1])
print(list[2])
print(list[3])
print(list[4])
print(list[5])
print(list[6])
print(list[7])
